# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: SpendHQ
description: SpendHQ Delegation Indexer - tracks agent redemptions and disabled delegation
contracts:
  - name: DelegationManager
    abi_file_path: ./abis/delegation-manager.json
    handler: ./src/EventHandlers.ts
    events:
      - event: EnabledDelegation
      - event: RedeemedDelegation
      - event: DisabledDelegation
networks:
  - id: 84532 # Base Sepolia
    start_block: 19490000
    contracts:
      - name: DelegationManager
        address: 0xdb9B1e94B5b69Df7e401DDbedE43491141047dB3
  - id: 11155111 # Sepolia
    start_block: 7558000
    contracts:
      - name: DelegationManager
        address: 0xdb9B1e94B5b69Df7e401DDbedE43491141047dB3
